=== Sweetzonzi/Machine-Max_BlockbenchPlugin/src/builtin/official_pack/machine_max/docs/zh_cn/schemas/part_definition_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://machine_max.io/schemas/part_definition_schema.json",
  "title": "部件定义",
  "description": "MachineMax载具部件的完整定义文件，这是创建自定义载具部件的顶层配置",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "JSON Schema引用路径，用于编辑器智能提示和验证",
      "default": "../../docs/zh_cn/schemas/part_definition_schema.json"
    },
    "icon": {
      "$ref": "base/resource_location.schema.json",
      "description": "部件图标路径，用于UI显示。若留空会使用紫黑缺省图标作为图标",
      "default": "minecraft:missingno"
    },
    "vehicle_durability_rate": {
      "type": "number",
      "minimum": 0,
      "maximum": 1.0,
      "default": 0.8,
      "description": "载具耐久贡献系数，部件耐久度按此比例贡献给载具总耐久度。例如0.8表示部件的80%耐久度贡献给载具"
    },
    "vehicle_damage_rate": {
      "type": "number",
      "minimum": 0,
      "default": 1.0,
      "description": "常态载具伤害传导系数，部件受到伤害时按此比例传导给载具。例如1.0表示100%伤害传导"
    },
    "vehicle_damage_rate_destroyed": {
      "type": "number",
      "minimum": 0,
      "default": 0.1,
      "description": "部件被摧毁后的载具伤害传导系数，部件被摧毁后受到伤害时按此比例传导给载具。通常设置较低以防止鞭尸"
    },
    "functional_threshold": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 1.0,
      "default": 0.3,
      "description": "部件功能阈值。当组装进度达到该值后，子系统可工作，且线框组装渲染可自动关闭。"
    },
    "share_durability": {
      "type": "boolean",
      "default": true,
      "description": "部件内零件是否共享耐久度。如果为true，所有子部件共享同一耐久度池；如果为false，每个子部件有独立耐久度"
    },
    "max_stack_size": {
      "type": "integer",
      "minimum": 1,
      "maximum": 64,
      "default": 1,
      "description": "部件物品的最大堆叠数量。决定此部件在物品栏中可以堆叠多少个。默认值为1（不可堆叠）"
    },
    "variants": {
      "oneOf": [
        {
          "$ref": "part/variant_attr.schema.json",
          "description": "单一变体定义，使用默认变体名（\"default\"）"
        },
        {
          "type": "object",
          "additionalProperties": {
            "$ref": "part/variant_attr.schema.json"
          },
          "minProperties": 1,
          "description": "多变体定义，键为变体名称（如\"red\"、\"blue\"、\"camouflage\"等），值为变体配置"
        }
      ],
      "description": "部件变体列表，常用作区分左右对称的部件如轮胎或手臂，支持单一变体（默认）或多个变体配置。每个变体可以有不同的外观和特性"
    }
  },
  "additionalProperties": false,
  "required": ["variants"],
  "examples": [
    {
      "$schema": "../../docs/zh_cn/schemas/part_definition_schema.json",
      "icon": "machine_max:textures/icon/ae86_chassis_all_terrain_icon.png",
      "vehicle_durability_rate": 1.0,
      "vehicle_damage_rate": 1.0,
      "vehicle_damage_rate_destroyed": 0.1,
      "functional_threshold": 0.6,
      "share_durability": true,
      "variants": {
        "models": "machine_max:ae86_chassis_all_terrain.geo",
        "textures": [
          "machine_max:textures/part/ae86_all_terrain_1.png",
          "machine_max:textures/part/ae86_all_terrain_2.png"
        ],
        "animations": "machine_max:ae86",
        "tags": [],
        "sub_parts": {
          "ae86_chassis_all_terrain": {
            "durability": 550.0,
            "mass": 1200.0,
            "hit_boxes": {
              "mmCollision_Box_Chassis": {
                "name": "chassis",
                "type": "box",
                "thickness": 10
              }
            }
          }
        }
      }
    },
    {
      "$schema": "../../docs/zh_cn/schemas/part_definition_schema.json",
      "icon": "machine_max:textures/icon/car_chassis_icon.png",
      "vehicle_durability_rate": 0.9,
      "variants": {
        "red": {
          "models": "machine_max:car_chassis.geo",
          "textures": ["machine_max:textures/part/car_chassis_red.png"],
          "sub_parts": {
            "chassis": {
              "durability": 400.0,
              "mass": 800.0,
              "hit_boxes": {
                "collision_box": {
                  "type": "box",
                  "thickness": 8
                }
              }
            }
          }
        },
        "blue": {
          "models": "machine_max:car_chassis.geo",
          "textures": ["machine_max:textures/part/car_chassis_blue.png"],
          "sub_parts": {
            "chassis": {
              "durability": 400.0,
              "mass": 800.0,
              "hit_boxes": {
                "collision_box": {
                  "type": "box",
                  "thickness": 8
                }
              }
            }
          }
        }
      }
    }
  ]
}

=== Sweetzonzi/Machine-Max_BlockbenchPlugin/src/builtin/official_pack/machine_max/parts/senna_gtr/senna_gtr_door.json
{
  "$schema": "../../docs/zh_cn/schemas/part_definition_schema.json",
  "icon": "machine_max:textures/icon/senna_gtr/senna_gtr_door_icon.png",
  "vehicle_durability_rate": 1.0,
  "vehicle_damage_rate": 0.5,
  "vehicle_damage_rate_destroyed": 0.1,
  "max_stack_size": 2,
  "variants": {
    "left": {
      "model": "machine_max:senna_gtr_door_left.geo",
      "textures": "machine_max:textures/part/senna_gtr/senna_gtr.png",
      "animations": "machine_max:empty",
      "tags": ["machine_max:door", "machine_max:senna_gtr", "machine_max:left"],
      "sub_parts": {
        "sub_part.machine_max.main": {
          "durability": 50.0,
          "mass": 35.0,
          "block_collision": "ground",
          "collision_height": 1.5,
          "hit_boxes": {
            "Collision": {
              "type": "box",
              "material": "machine_max:7035_aluminum_alloy"
            }
          },
          "connectors": {
            "connector.machine_max.axis": {
              "locator": "left_door_hull_axis",
              "definition": "machine_max:fixed_down",
              "overwrite": {
                "integrity": 5
              }
            },
            "connector.machine_max.lock": {
              "locator": "left_door_hull_lock",
              "definition": "machine_max:fixed_down"
            }
          },
          "projected_area": [0.19, 1.04, 0.29],
          "hydrodynamics": {
            "": {
              "front_drag": [0.1, 0.1],
              "back_drag": [0.1, 0.1]
            }
          }
        }
      }
    },
    "right": {
      "model": "machine_max:senna_gtr_door_right.geo",
      "textures": "machine_max:textures/part/senna_gtr/senna_gtr.png",
      "animations": "machine_max:empty",
      "tags": ["machine_max:door", "machine_max:senna_gtr", "machine_max:right"],
      "sub_parts": {
        "sub_part.machine_max.main": {
          "durability": 50.0,
          "mass": 35.0,
          "block_collision": "ground",
          "collision_height": 1.5,
          "hit_boxes": {
            "Collision": {
              "type": "box",
              "material": "machine_max:7035_aluminum_alloy"
            }
          },
          "connectors": {
            "connector.machine_max.axis": {
              "locator": "right_door_hull_axis",
              "definition": "machine_max:fixed_down"
            },
            "connector.machine_max.lock": {
              "locator": "right_door_hull_lock",
              "definition": "machine_max:fixed_down",
              "overwrite": {
                "integrity": 5
              }
            }
          },
          "projected_area": [0.19, 1.04, 0.29],
          "hydrodynamics": {
            "": {
              "front_drag": [0.1, 0.1],
              "back_drag": [0.1, 0.1]
            }
          }
        }
      }
    }
  }
}

=== Sweetzonzi/Machine-Max_BlockbenchPlugin/src/builtin/official_pack/machine_max/parts/jeep/jeep_chassis.json
{
  "$schema": "../../docs/zh_cn/schemas/part_definition_schema.json",
  "icon": "machine_max:textures/icon/jeep/jeep_chassis_icon.png",
  "vehicle_durability_rate": 1.0,
  "vehicle_damage_rate": 1.0,
  "vehicle_damage_rate_destroyed": 0.1,
  "variants": {
    "model": "machine_max:jeep_chassis.geo",
    "textures": {
      "print.machine_max.yellow": "machine_max:textures/part/jeep/jeep1.png",
      "print.machine_max.white": "machine_max:textures/part/jeep/jeep2.png"
    },
    "animations": "machine_max:jeep",
    "tags": ["machine_max:jeep", "machine_max:chassis", "machine_max:storage"],
    "sub_parts": {
      "sub_part.machine_max.main": {
        "durability": 900.0,
        "mass": 950.0,
        "block_collision": "ground",
        "collision_height": 2.5,
        "hit_boxes": {
          "collision": {
            "type": "box",
            "material": "machine_max:structural_steel",
            "thickness": 5
          },
          "collision_engine": {
            "type": "box",
            "subsystem": "subsystem.machine_max.engine",
            "material": "machine_max:structural_steel",
            "thickness": 2
          }
        },
        "interact_boxes": {
          "interact.machine_max.left_seat": {
            "bone": "interact_left_seat",
            "signal_targets": {
              "left_seat_interact": ["subsystem.machine_max.driver_seat"]
            },
            "interact_mode": "accurate"
          },
          "interact.machine_max.right_seat": {
            "bone": "interact_right_seat",
            "signal_targets": {
              "right_seat_interact": ["subsystem.machine_max.copilot_seat"]
            },
            "interact_mode": "accurate"
          },
          "interact.machine_max.left_glove_box": {
            "bone": "interact_left_glove_box",
            "signal_targets": {
              "left_glove_box_interact": ["subsystem.machine_max.left_glove_box"]
            },
            "interact_mode": "accurate"
          },
          "interact.machine_max.right_glove_box": {
            "bone": "interact_right_glove_box",
            "signal_targets": {
              "right_glove_box_interact": ["subsystem.machine_max.right_glove_box"]
            },
            "interact_mode": "accurate"
          }
        },
        "subsystems": {
          "subsystem.machine_max.driver_seat": {
            "type": "machine_max:seat",
            "definition": "machine_max:default_seat",
            "locator": "seat_point_left",
            "move_outputs": {
              "move_control": [
                "subsystem.machine_max.car_controller"
              ]
            },
            "regular_outputs": {
              "regular_control": [
                "subsystem.machine_max.car_controller"
              ]
            },
            "aim_outputs": {
              "aim_control": [
                "subsystem.machine_max.car_controller"
              ]
            },
            "passenger_num_outputs": {
              "driver_occupied": ["interact.machine_max.left_seat", "connector.machine_max.hull_connection"]
            }
          },
          "subsystem.machine_max.copilot_seat": {
            "type": "machine_max:seat",
            "definition": "machine_max:default_passenger_seat",
            "locator": "seat_point_right",
            "passenger_num_outputs": {
              "copilot_occupied": ["interact.machine_max.right_seat", "connector.machine_max.hull_connection"]
            }
          },
          "subsystem.machine_max.car_controller": {
            "type": "machine_max:car_controller",
            "definition": "machine_max:jeep_car_controller",
            "control_outputs": {
              "car_control": [
                "subsystem.machine_max.engine",
                "subsystem.machine_max.gearbox",
                "subsystem.machine_max.left_back_wheel_driver",
                "subsystem.machine_max.left_front_wheel_driver",
                "subsystem.machine_max.right_back_wheel_driver",
                "subsystem.machine_max.right_front_wheel_driver"
              ]
            },
            "speed_outputs": {
              "vehicle_speed": [
                "vehicle"
              ]
            },
            "throttle_outputs": {
              "throttle": [
                "vehicle"
              ]
            },
            "brake_outputs": {
              "brake": [
                "vehicle"
              ]
            },
            "steering_outputs": {
              "steering": [
                "vehicle"
              ]
            },
            "handbrake_outputs": {
              "handbrake": [
                "vehicle"
              ]
            }
          },
          "subsystem.machine_max.engine": {
            "type": "machine_max:engine",
            "definition": "machine_max:jeep_engine",
            "power_output": "subsystem.machine_max.gearbox",
            "speed_outputs": {
              "engine_speed": [
                "vehicle"
              ]
            }
          },
          "subsystem.machine_max.gearbox": {
            "type": "machine_max:gearbox",
            "definition": "machine_max:jeep_gearbox",
            "power_output": "subsystem.machine_max.transmission",
            "gear_outputs": {
              "gear": [
                "vehicle"
              ]
            }
          },
          "subsystem.machine_max.transmission": {
            "type": "machine_max:transmission",
            "definition": "machine_max:jeep_transmission",
            "power_outputs": {
              "subsystem.machine_max.left_front_wheel_driver": 1.0,
              "subsystem.machine_max.right_front_wheel_driver": 1.0,
              "subsystem.machine_max.left_back_wheel_driver": 1.0,
              "subsystem.machine_max.right_back_wheel_driver": 1.0
            }
          },
          "subsystem.machine_max.left_front_wheel_driver": {
            "type": "machine_max:wheel_driver",
            "definition": "machine_max:jeep_front_wheel_driver",
            "connector": "connector.machine_max.left_front_wheel"
          },
          "subsystem.machine_max.right_front_wheel_driver": {
            "type": "machine_max:wheel_driver",
            "definition": "machine_max:jeep_front_wheel_driver",
            "connector": "connector.machine_max.right_front_wheel"
          },
          "subsystem.machine_max.left_back_wheel_driver": {
            "type": "machine_max:wheel_driver",
            "definition": "machine_max:jeep_back_wheel_driver",
            "connector": "connector.machine_max.left_back_wheel"
          },
          "subsystem.machine_max.right_back_wheel_driver": {
            "type": "machine_max:wheel_driver",
            "definition": "machine_max:jeep_back_wheel_driver",
            "connector": "connector.machine_max.right_back_wheel"
          },
          "subsystem.machine_max.left_glove_box": {
            "type": "machine_max:item_storage",
            "definition": "machine_max:glove_box"
          },
          "subsystem.machine_max.right_glove_box": {
            "type": "machine_max:item_storage",
            "definition": "machine_max:glove_box"
          }
        },
        "connectors": {
          "connector.machine_max.left_front_wheel": {
            "locator": "left_front_wheel",
            "definition": "machine_max:jeep_left_steering_wheel"
          },
          "connector.machine_max.left_back_wheel": {
            "locator": "left_back_wheel",
            "definition": "machine_max:jeep_left_wheel"
          },
          "connector.machine_max.right_back_wheel": {
            "locator": "right_back_wheel",
            "definition": "machine_max:jeep_right_wheel"
          },
          "connector.machine_max.right_front_wheel": {
            "locator": "right_front_wheel",
            "definition": "machine_max:jeep_right_steering_wheel"
          },
          "connector.machine_max.hull_connection": {
            "locator": "hull",
            "definition": "machine_max:fixed_up",
            "signal_targets": {
              "interact_left_door": ["subsystem.machine_max.driver_seat"],
              "interact_right_door": ["subsystem.machine_max.copilot_seat"]
            }
          },
          "connector.machine_max.trunk": {
            "locator": "trunk",
            "definition": "machine_max:fixed_up"
          }
        },
        "hydro_priority": 1,
        "hydrodynamics": {
          "": {
            "front_drag": [0.1, 0.2],
            "back_drag": [0.1, 0.4]
          }
        }
      }
    }
  }
}

=== Sweetzonzi/Machine-Max_BlockbenchPlugin/src/builtin/official_pack/machine_max/parts/senna_gtr/senna_gtr_hull.json
{
  "$schema": "../../docs/zh_cn/schemas/part_definition_schema.json",
  "icon": "machine_max:textures/icon/senna_gtr/senna_gtr_hull_icon.png",
  "vehicle_durability_rate": 0.6,
  "vehicle_damage_rate": 1.0,
  "vehicle_damage_rate_destroyed": 0.1,
  "variants": {
    "front": {
      "model": "machine_max:senna_gtr_front_hull.geo",
      "textures": "machine_max:textures/part/senna_gtr/senna_gtr.png",
      "animations": "machine_max:senna_gtr",
      "tags": ["machine_max:hull", "machine_max:senna_gtr", "machine_max:front"],
      "sub_parts": {
        "sub_part.machine_max.main": {
          "durability": 120.0,
          "mass": 50.0,
          "block_collision": "ground",
          "collision_height": 1.5,
          "hit_boxes": {
            "Collision": {
              "id": "part",
              "type": "box",
              "material": "machine_max:7035_aluminum_alloy"
            }
          },
          "connectors": {
            "connector.machine_max.chassis_front": {
              "locator": "hull_chassis_front",
              "definition": "machine_max:fixed_down"
            },
            "connector.machine_max.left_door_axis": {
              "locator": "hull_left_door_axis",
              "definition": "machine_max:senna_gtr_left_door_axis"
            },
            "connector.machine_max.right_door_axis": {
              "locator": "hull_right_door_axis",
              "definition": "machine_max:senna_gtr_right_door_axis"
            }
          },
          "projected_area": [4.6, 6.9, 5.5],
          "hydro_priority": 10,
          "hydrodynamics": {
            "": {
              "front_drag": [0.1, 0.1],
              "back_drag": [0.1, 0.0]
            }
          }
        }
      }
    },
    "back": {
      "model": "machine_max:senna_gtr_back_hull.geo",
      "textures": "machine_max:textures/part/senna_gtr/senna_gtr.png",
      "animations": "machine_max:senna_gtr",
      "tags": ["machine_max:hull", "machine_max:senna_gtr", "machine_max:back"],
      "sub_parts": {
        "sub_part.machine_max.main": {
          "durability": 120.0,
          "mass": 50.0,
          "block_collision": "ground",
          "collision_height": 1.5,
          "hit_boxes": {
            "Collision": {
              "id": "part",
              "type": "box",
              "material": "machine_max:7035_aluminum_alloy"
            }
          },
          "connectors": {
            "connector.machine_max.chassis_back": {
              "locator": "hull_chassis_back",
              "definition": "machine_max:fixed_down"
            },
            "connector.machine_max.left_door_lock": {
              "locator": "hull_left_door_lock",
              "definition": "machine_max:fixed_up"
            },
            "connector.machine_max.right_door_lock": {
              "locator": "hull_right_door_lock",
              "definition": "machine_max:fixed_up"
            }
          },
          "projected_area": [4.6, 6.9, 5.5],
          "hydro_priority": 10,
          "hydrodynamics": {
            "": {
              "front_drag": [0.1, 0.05],
              "back_drag": [0.1, 0.1],
              "y_lift": -0.001
            }
          }
        }
      }
    }
  }
}

=== Sweetzonzi/Machine-Max_BlockbenchPlugin/src/builtin/official_pack/machine_max/parts/ae86/ae86_armor.json
{
  "$schema": "../../docs/zh_cn/schemas/part_definition_schema.json",
  "icon": "machine_max:textures/icon/ae86/ae86_armor_icon.png",
  "vehicle_durability_rate": 1.0,
  "vehicle_damage_rate": 0.1,
  "vehicle_damage_rate_destroyed": 0.1,
  "variants": {
    "model": "machine_max:ae86_armor.geo",
    "textures": {
      "default": "machine_max:textures/part/ae86/ae86_armor.png"
    },
    "tags": ["machine_max:ae86"],
    "sub_parts": {
      "sub_part.machine_max.main": {
        "durability": 1200.0,
        "mass": 10.0,
        "block_collision": "true",
        "collision_height": 0,
        "hit_boxes": {
          "collision_armor": {
            "type": "box",
            "material": "machine_max:structural_steel",
            "thickness": 5
          }
        },
        "connectors": {
          "connector.machine_max.front_armor": {
            "locator": "front_armor",
            "definition": "machine_max:fixed_down"
          }
        }
      }
    }
  }
}
